using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSystem.Models
{
    [Index(nameof(LoginId), IsUnique = true)]
    [Index(nameof(Email), IsUnique = true)]
    public class User
    {
        [Key]
        public int Id { get; set; }

        // Login ID:
        // Student    → EnrollmentNumber
        // Faculty    → EmployeeId
        // Librarian  → EmployeeId
        [MaxLength(50)]
        public string? LoginId { get; set; }

        // -----------------------
        // STUDENT FIELDS
        // -----------------------
        public string? EnrollmentNumber { get; set; } 
        public string? Year { get; set; }
        public string? Semester { get; set; }

        // -----------------------
        // COMMON FIELDS
        // -----------------------
        [Required]
        public string FullName { get; set; } = null!;

        [Required, EmailAddress]
        public string Email { get; set; } = null!;

        [Required]
        public string Phone { get; set; } = null!;

        // Password is generated by admin on approval
        public string? PasswordHash { get; set; }

        [Required]
        public string Gender { get; set; } = null!;

        [Required]
        public string Department { get; set; } = null!;

        // Student / Faculty / Librarian / Admin (if needed)
        [Required]
        public string Role { get; set; } = null!;

        [DataType(DataType.Date)]
        public DateTime? DateOfBirth { get; set; }

        [MaxLength(200)]
        public string? Address { get; set; }

        public string? ProfileImageFileName { get; set; }
        public string? ProfilePicturePath { get; set; }

        // -----------------------
        // STATUS FIELDS
        // -----------------------
        public bool IsApproved { get; set; } = false;
        public DateTime RegisteredAt { get; set; } = DateTime.UtcNow;
        public DateTime? ApprovedAt { get; set; }

        // -----------------------
        // SOFT DELETE
        // -----------------------
        public bool IsDeleted { get; set; } = false;
        public DateTime? DeletedAt { get; set; }
        public string? DeletedBy { get; set; }
    }
}
